---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rancher/system-upgrade-controller.git?ref=v0.14.1

# Upstream hardcodes image version to an old version
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.14.1
